import type { Metadata } from "next";
import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackgroundPrismatic from "../components/BackgroundPrismatic";
import SiteNav from "../components/SiteNav";
import { LanguageProvider } from "../lib/LanguageProvider";

const roboto = Roboto({
  variable: "--font-geist-sans", // reutilizamos la var CSS esperada por globals.css
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Qiu Automations",
  description: "Generated by create next app",  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${roboto.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <BackgroundPrismatic />
          <SiteNav />
          <div className="relative z-10">{children}</div>
        </LanguageProvider>
      </body>
    </html>
  );
}
